import { Injectable } from '@angular/core';
import { UserTable } from '../../Datatypes';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class UserService {
  private generateRandomId(): string {
    return Math.random().toString(36).substring(2, 10); // Erzeugt eine zufällige alphanumerische ID
  }
  getUsers(): Observable<UserTable[]> {
    return of([
      {
        id: this.generateRandomId(),
        fullName: 'Alice Smith',
        email: 'alice.smith@example.com',
        phone: '+1-202-555-0175',
        dateOfBirth: '1985-03-23',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Bob Johnson',
        email: 'bob.johnson@example.com',
        phone: '+1-202-555-0198',
        dateOfBirth: '1978-07-11',
      },
      {
        id: this.generateRandomId(),
        fullName: 'David Brown',
        email: 'david.brown@example.com',
        phone: '+1-202-555-0189',
        dateOfBirth: '1990-10-09',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Frank Garcia',
        email: 'frank.garcia@example.com',
        phone: '+1-202-555-0144',
        dateOfBirth: '1983-02-14',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Hank Miller',
        email: 'hank.miller@example.com',
        phone: '+1-202-555-0125',
        dateOfBirth: '1992-06-30',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Jack Moore',
        email: 'jack.moore@example.com',
        phone: '+1-202-555-0162',
        dateOfBirth: '1987-12-25',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Leo Anderson',
        email: 'leo.anderson@example.com',
        phone: '+1-202-555-0133',
        dateOfBirth: '1975-04-12',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Noah Jackson',
        email: 'noah.jackson@example.com',
        phone: '+1-202-555-0155',
        dateOfBirth: '1993-09-15',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Paul Harris',
        email: 'paul.harris@example.com',
        phone: '+1-202-555-0191',
        dateOfBirth: '1984-08-08',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Ruth Thompson',
        email: 'ruth.thompson@example.com',
        phone: '+1-202-555-0167',
        dateOfBirth: '1972-11-30',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Tina Lee',
        email: 'tina.lee@example.com',
        phone: '+1-202-555-0188',
        dateOfBirth: '1989-05-05',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Vera Hall',
        email: 'vera.hall@example.com',
        phone: '+1-202-555-0114',
        dateOfBirth: '1991-03-10',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Xander King',
        email: 'xander.king@example.com',
        phone: '+1-202-555-0178',
        dateOfBirth: '1995-10-18',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Zoe Green',
        email: 'zoe.green@example.com',
        phone: '+1-202-555-0152',
        dateOfBirth: '1980-12-02',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Bella Rivera',
        email: 'bella.rivera@example.com',
        phone: '+1-202-555-0104',
        dateOfBirth: '1988-09-24',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Diana Ward',
        email: 'diana.ward@example.com',
        phone: '+1-202-555-0173',
        dateOfBirth: '1982-01-18',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Fiona Torres',
        email: 'fiona.torres@example.com',
        phone: '+1-202-555-0183',
        dateOfBirth: '1994-05-11',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Holly Morgan',
        email: 'holly.morgan@example.com',
        phone: '+1-202-555-0164',
        dateOfBirth: '1976-07-26',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Jade Gonzales',
        email: 'jade.gonzales@example.com',
        phone: '+1-202-555-0128',
        dateOfBirth: '1992-03-07',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Kurt Reed',
        email: 'kurt.reed@example.com',
        phone: '+1-202-555-0116',
        dateOfBirth: '1985-08-30',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Lily Cox',
        email: 'lily.cox@example.com',
        phone: '+1-202-555-0147',
        dateOfBirth: '1990-11-12',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Nina Kelly',
        email: 'nina.kelly@example.com',
        phone: '+1-202-555-0179',
        dateOfBirth: '1979-03-29',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Oscar Ramirez',
        email: 'oscar.ramirez@example.com',
        phone: '+1-202-555-0194',
        dateOfBirth: '1986-07-19',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Piper Ward',
        email: 'piper.ward@example.com',
        phone: '+1-202-555-0140',
        dateOfBirth: '1993-12-06',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Quincy Price',
        email: 'quincy.price@example.com',
        phone: '+1-202-555-0180',
        dateOfBirth: '1995-06-21',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Ruby Sanders',
        email: 'ruby.sanders@example.com',
        phone: '+1-202-555-0129',
        dateOfBirth: '1977-04-03',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Sean Griffin',
        email: 'sean.griffin@example.com',
        phone: '+1-202-555-0169',
        dateOfBirth: '1994-09-16',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Tara Diaz',
        email: 'tara.diaz@example.com',
        phone: '+1-202-555-0172',
        dateOfBirth: '1981-05-14',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Violet Barnes',
        email: 'violet.barnes@example.com',
        phone: '+1-202-555-0135',
        dateOfBirth: '1989-02-24',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Wesley Ross',
        email: 'wesley.ross@example.com',
        phone: '+1-202-555-0156',
        dateOfBirth: '1973-11-04',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Alan Carter',
        email: 'alan.carter@example.com',
        phone: '+1-202-555-0185',
        dateOfBirth: '1983-01-10',
      },
      {
        id: this.generateRandomId(),
        fullName: 'George Nguyen',
        email: 'george.nguyen@example.com',
        phone: '+1-202-555-0107',
        dateOfBirth: '1992-10-21',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Ethan Flores',
        email: 'ethan.flores@example.com',
        phone: '+1-202-555-0121',
        dateOfBirth: '1984-12-30',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Chris Howard',
        email: 'chris.howard@example.com',
        phone: '+1-202-555-0158',
        dateOfBirth: '1988-05-22',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Max Rogers',
        email: 'max.rogers@example.com',
        phone: '+1-202-555-0190',
        dateOfBirth: '1991-11-17',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Ian Bell',
        email: 'ian.bell@example.com',
        phone: '+1-202-555-0187',
        dateOfBirth: '1987-06-29',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Uma Perez',
        email: 'uma.perez@example.com',
        phone: '+1-202-555-0132',
        dateOfBirth: '1990-02-07',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Grace Martinez',
        email: 'grace.martinez@example.com',
        phone: '+1-202-555-0148',
        dateOfBirth: '1986-09-08',
      },
      {
        id: this.generateRandomId(),
        fullName: 'Will Young',
        email: 'will.young@example.com',
        phone: '+1-202-555-0148',
        dateOfBirth: '1986-09-08',
      },
    ]);
  }
}
